default:
  outputs:
    dev:
      type: postgres
      host: postgres # The name of the Postgres service in your Docker Compose file
      user: postgres # Default Postgres user
      password: '123' # The password you set for Postgres
      port: 5432 # Default Postgres port
      dbname: postgres # Default Postgres database name
      schema: public
  target: dev