services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 123
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  airflow:
    build:
      context: ./airflow
    environment:
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:123@postgres/postgres
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./data:/data
    ports:
      - 8080:8080
    depends_on:
      - postgres

  redash:
    image: redash/redash:latest
    environment:
      REDASH_HOST: http://localhost
      REDASH_BACKEND_POSTGRESQL_URL: "postgresql://postgres:123@postgres/postgres"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:5000"

volumes:
  postgres-data:
  redash-data:
